server:
  port: 8081
spring:
  application:
    name: dianping
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hmdp?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 12345678
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 32
        max-idle: 16
        min-idle: 8
        time-between-eviction-runs: 10s
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        prefetch: 1
        acknowledge-mode: manual
  jackson:
    default-property-inclusion: non_null
mybatis-plus:
  type-aliases-package: com.hmdp.entity
logging:
  level:
    com.hmdp: debug
  pattern:
    dateformat: mm:ss.SSS